# Generated by Django 2.1.2 on 2018-12-03 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('itemid', models.CharField(max_length=50)),
                ('ownername', models.CharField(max_length=50)),
                ('buyername', models.CharField(max_length=50)),
                ('buyeremail', models.EmailField(max_length=100)),
                ('buyerphone', models.CharField(max_length=20)),
                ('commenttext', models.TextField()),
                ('commentdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Confirmation Code',
                'verbose_name_plural': 'Confirmation Code',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='item_image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('condition', models.CharField(max_length=50)),
                ('keyword', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='Not Selected', max_length=50)),
                ('userid', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('itemid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCate',
            fields=[
                ('parentid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parentname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCate',
            fields=[
                ('subid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=100)),
                ('parentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ParentCate')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='user', max_length=100)),
                ('password', models.CharField(default='password1', max_length=100)),
                ('phonenumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.UserProfile'),
        ),
    ]
