# Generated by Django 2.1.2 on 2018-10-31 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('condition', models.CharField(max_length=50)),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='ParentCate',
            fields=[
                ('parentid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parentname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCate',
            fields=[
                ('subid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=100)),
                ('parentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ParentCate')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Admin')),
                ('useritemid', models.ManyToManyField(blank=True, to='market.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.SubCate'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_id', to='market.SubCate'),
        ),
        migrations.AddField(
            model_name='item',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User'),
        ),
    ]
