# Generated by Django 2.1.1 on 2018-11-03 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('7c6ff5dd-edbb-464c-9fce-1049bdf3fb62'), primary_key=True, serialize=False),
        ),
    ]
