# Generated by Django 2.1.1 on 2018-11-03 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_auto_20181103_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userid', models.UUIDField(default=uuid.UUID('2cae0996-0074-4ae2-b137-c53ee6056dc2'), primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100)),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Admin')),
            ],
            options={
                'verbose_name': 'User Profile',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='adminid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='useritemid',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('6c3b4006-466c-4c18-86ed-d245c9ae9a39'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
