# Generated by Django 2.1.1 on 2018-11-03 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20181103_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('8224d137-5062-4684-a943-da6f12732ea0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('da57b055-6ff1-4805-b17a-7c418acbe3f0'), primary_key=True, serialize=False),
        ),
    ]
