# Generated by Django 2.1.1 on 2018-11-03 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20181103_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('0620d454-d8ce-4cdd-b0a4-591cf78a0522'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('68c1b539-47d1-4fb8-9723-5c8c06c4c7a3'), primary_key=True, serialize=False),
        ),
    ]
