# Generated by Django 2.1.1 on 2018-11-03 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20181103_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('433ece86-b034-4f90-80e4-04d130b89f2e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('32a71c34-8cb0-421f-8399-f4101fb77163'), primary_key=True, serialize=False),
        ),
    ]
