# Generated by Django 2.1.1 on 2018-11-10 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20181110_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('1be2eb5d-9fe3-4dc9-9d80-41d0cebb520b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('58f4828f-f579-4bc5-9f77-de293c61bad2'), primary_key=True, serialize=False),
        ),
    ]
