# Generated by Django 2.1.1 on 2018-11-10 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20181110_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password1',
            field=models.CharField(default='password1', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password2',
            field=models.CharField(default='password2', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('399d95df-8464-40ed-b314-8703cb3c643f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('23a6331b-3ce0-4b27-85ce-f6891f83fda3'), primary_key=True, serialize=False),
        ),
    ]
