# Generated by Django 2.1.1 on 2018-11-10 22:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20181110_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('f9782173-c8a4-49ae-9776-70e8dc6f6c5e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='adminid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='market.Admin'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('022a910b-1ca1-45bf-b930-28744cebbc55'), primary_key=True, serialize=False),
        ),
    ]
