# Generated by Django 2.1.1 on 2018-11-10 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20181110_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adminid',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('e2d5ae8b-cdea-4879-9ef3-3d4860fb96e7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('5d2168a2-c769-42ee-ae28-a422f1d59a24'), primary_key=True, serialize=False),
        ),
    ]
