# Generated by Django 2.1.1 on 2018-11-10 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20181110_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('0771645f-868c-4b6c-91d5-5d3035205bdf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('b424bf87-0edf-4b26-a4c6-96affab45f63'), primary_key=True, serialize=False),
        ),
    ]
