# Generated by Django 2.1.2 on 2018-11-27 01:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20181110_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password2',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('6e520abc-0747-423f-88f2-6c5326d07b10'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('4f3fc8a5-3ab9-41ba-b2ba-6440841e538b'), primary_key=True, serialize=False),
        ),
    ]
