# Generated by Django 2.1.2 on 2018-11-27 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20181126_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('c883662c-22eb-434b-ad6b-a7cdcdfca995'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('ed658f89-ad09-4840-8106-3dadd16596ff'), primary_key=True, serialize=False),
        ),
    ]
