# Generated by Django 2.1.2 on 2018-11-27 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_auto_20181126_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('dc1d3715-2622-44f5-a7a7-c2cfec3a91f0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('fe4836c5-06d5-4abc-8792-947b5b882e70'), primary_key=True, serialize=False),
        ),
    ]
