# Generated by Django 2.1.2 on 2018-11-27 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_auto_20181126_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('2fc25e66-b645-4794-8bf0-11ce44dbe2db'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('3c4ed18b-ccaf-450c-999d-61a76134663e'), primary_key=True, serialize=False),
        ),
    ]
