# Generated by Django 2.1.2 on 2018-11-30 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20181126_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('7763e1ac-d957-41d4-8640-66b29324ed18'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, upload_to='item_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('96286845-1a80-4056-a8ea-2598b3413edb'), primary_key=True, serialize=False),
        ),
    ]
