# Generated by Django 2.1.2 on 2018-11-30 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20181129_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='userid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('a4fd86da-4873-4fdf-ab9b-162b9b51a19c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('9d32fc9e-75bc-4c7a-84a9-cd14e6675d4e'), primary_key=True, serialize=False),
        ),
    ]
