# Generated by Django 2.1.2 on 2018-11-30 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_auto_20181130_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('fa68738c-207f-4c65-b421-dbf3c6777952'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('b46dda99-3489-4173-8990-85babb1ffb6d'), primary_key=True, serialize=False),
        ),
    ]
