# Generated by Django 2.1.2 on 2018-11-30 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_auto_20181130_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('715b5a03-d3c5-4104-9bb7-cd9aefe36685'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('5af5a600-c0e5-44d0-88d3-d286710edf6b'), primary_key=True, serialize=False),
        ),
    ]
